### ISSUE TITLE
Addition of GCM encryption?

### ISSUE THREAD

**Issue by l0k1verloren** [xtaci/kcp-go#108]
This is not a request so much as an offer to add this encryption mode to kcp-go. Out of all the encryption options, only AES really qualifies as both fast and secure, but for relatively short lived sessions with under 4gb of total data transfer per session key, GCM is faster.

As a somewhat side issue, what ways are recommended for securely creating an ad-hoc session cipher? To be honest it's not something I have any experience with yet, but I will look also at this.

Is this a good one? https://github.com/wsddn/go-ecdh

**Comment by xtaci** [comment]
Maybe not faster, since for each outgoing UDP packet, nonces are renewed, galois counter needs to re-initiated for every packet, and be invalidated in next round, counters cannot be pre-calculated compared to stream based long session. 

It cannot be faster than in CFB mode, which nothing required to setup.

**Comment by l0k1verloren** [comment]
Ah, ok, yes I wasn't aware of that, and of course that puts serious limits on its performance (entropy). I'll close this issue. I have looked at several dh session key libraries and it looks like it would not be hard to negotiate this at the beginning of a session anyway. I'll close the issue.
