### ISSUE TITLE
all queued messages are dropped when call UDPSession.Close()

### ISSUE THREAD

**Issue by xjdrew** [xtaci/kcp-go#144]
when close, kcp-go drops all queued messages especially ack packet. 

Code: 
https://github.com/xtaci/kcp-go/blob/master/sess.go#L349

TCP's default behavior when close, is to send all queued messages in the background, refer to: http://man7.org/linux/man-pages/man7/socket.7.html#SO_LINGER

should try best to send all queued messages when close udp session.

**Comment by xtaci** [comment]
for each `sess.Write()`, data will be sent on wire(assume `WriteDelay(false)`), then what's left behind are those packets unacknowledged by the peer.

Implementing SO_LINGER needs a background closing scheme to enable retransmission of packets, especially to retransmit those FIN/RST packets. BUT the problem here is: KCP has no FIN packets to stop the peer from sending more packets, lacking FIN packets made KCP unable to close the session in the way TCP SO_LINGER acts, remember the only way to close a KCP connections is TIMEOUT.

**Comment by xjdrew** [comment]
There is no graceful way to close kcp session, I think it's the protocol's weak. Maybe no solution by now.

But in practice, kcp-go package could have more user-friendly implemention when close session。

**Comment by xtaci** [comment]
| pending | (snd_una)  inflight and RTO (snd_nxt) |  acknowledge |

window := [snd_una, snd_nxt）

simply by calling flush() won't  slide the window to send pending data

**Comment by xjdrew** [comment]
it's only a try to send pending data, no problem if window is not available.
But it can solve the problem belows.
While testing a appliction based on kcp-go in local network,  I find when the client closes the session, the server always resends the last packet until timeout. Because the client have no chance to send the  last  packets' ack packet.

If only to solve the problem, this PR call kcp.flush with true is enough. I think there is no significant performance loss if call kcp.flush with false, but can benefit in some situation.

**Comment by xtaci** [comment]
for this particular situation, it's ok
and for the code, you need to lock before flush
